ci/linting: add job to check if there is a merge commit
The currently merging strategy for the project is `fast-forward`,
for this reason, this patch adds a job to prevent Merge Requests
that contains any merge patch.

Signed-off-by: Leandro Belli <leandro.belli@arm.com>
Change-Id: Ibad23c0ec4803dda1fa6065e585f2475be110d44

diff --git a/.gitlab/templates/linting.yml b/.gitlab/templates/linting.yml
--- a/.gitlab/templates/linting.yml
+++ b/.gitlab/templates/linting.yml
@@ -31,3 +31,15 @@
     expire_in: 2 days
     paths:
       - code-style.patch
+
+.check-for-merge-commits:
+  image: ${CI_REGISTRY_IMAGE}/ci-base:latest
+  script:
+    - |
+      merge_count=$(git log --merges --oneline \
+        $CI_MERGE_REQUEST_DIFF_BASE_SHA..HEAD | wc -l)
+      if [ $merge_count -gt 0 ]; then
+        echo "Error: There are merge commits in the specified range."
+        exit 1
+      fi
+      echo "SUCCESS: No merge commits in range."
